### ISSUE TITLE
When open Cmake file it gives error code 1 but it works

### ISSUE THREAD

**Issue by salimp2009** [Decodetalkers/neocmakelsp#24]
Hi 
I have started using neocmake and when I open a Cmake file, neovim gives an error message exit code 1 but lsp works.  
![image](https://github.com/Decodetalkers/neocmakelsp/assets/46407603/1ac9184a-9e8f-4ddb-8cf3-bf859807b8e9)

I used the config given here. I am using nvim-lspconfig , neovim 0.9.0 . Here is the :LspInfo out
![image](https://github.com/Decodetalkers/neocmakelsp/assets/46407603/c0519812-5a85-49d4-bada-7bf9fb2a2005)
Both hover and go to definition, completion everything is working.  here is :LspLog 
```
[START][2023-10-09 21:28:27] LSP logging initiated
[ERROR][2023-10-09 21:28:27] .../vim/lsp/rpc.lua:734	"rpc"	"/home/salim/.local/share/nvim/mason/bin/cmake-language-server"	"stderr"	'Traceback (most recent call last):\n  File "/home/salim/.local/share/nvim/mason/bin/cmake-language-server", line 8, in <module>\n'
[ERROR][2023-10-09 21:28:27] .../vim/lsp/rpc.lua:734	"rpc"	"/home/salim/.local/share/nvim/mason/bin/cmake-language-server"	"stderr"	'    sys.exit(main())\n             ^^^^^^\n  File "/home/salim/.local/share/nvim/mason/packages/cmake-language-server/venv/lib/python3.11/site-packages/cmake_language_server/server.py", line 263, in main\n    CMakeLanguageServer("cmake-language-server", __version__).start_io()  # type: ignore\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n'
[ERROR][2023-10-09 21:28:27] .../vim/lsp/rpc.lua:734	"rpc"	"/home/salim/.local/share/nvim/mason/bin/cmake-language-server"	"stderr"	'  File "/home/salim/.local/share/nvim/mason/packages/cmake-language-server/venv/lib/python3.11/site-packages/cmake_language_server/server.py", line 207, in __init__\n'
[ERROR][2023-10-09 21:28:27] .../vim/lsp/rpc.lua:734	"rpc"	"/home/salim/.local/share/nvim/mason/bin/cmake-language-server"	"stderr"	'    @self.feature(\n     ^^^^^^^^^^^^^\n  File "/home/salim/.local/share/nvim/mason/packages/cmake-language-server/venv/lib/python3.11/site-packages/pygls/feature_manager.py", line 192, in decorator\n    if options_type and not is_instance(options, options_type):\n                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n'
[ERROR][2023-10-09 21:28:27] .../vim/lsp/rpc.lua:734	"rpc"	"/home/salim/.local/share/nvim/mason/bin/cmake-language-server"	"stderr"	'  File "/home/salim/.local/share/nvim/mason/packages/cmake-language-server/venv/lib/python3.11/site-packages/pygls/lsp/__init__.py", line 136, in is_instance\n'
[ERROR][2023-10-09 21:28:27] .../vim/lsp/rpc.lua:734	"rpc"	"/home/salim/.local/share/nvim/mason/bin/cmake-language-server"	"stderr"	'    check_type(o, t)\n  File "/home/salim/.local/share/nvim/mason/packages/cmake-language-server/venv/lib/python3.11/site-packages/typeguard/_functions.py", line 74, in check_type\n'
[ERROR][2023-10-09 21:28:27] .../vim/lsp/rpc.lua:734	"rpc"	"/home/salim/.local/share/nvim/mason/bin/cmake-language-server"	"stderr"	'    check_type_internal(value, expected_type, memo)\n  File "/home/salim/.local/share/nvim/mason/packages/cmake-language-server/venv/lib/python3.11/site-packages/typeguard/_checkers.py", line 680, in check_type_internal\n'
[ERROR][2023-10-09 21:28:27] .../vim/lsp/rpc.lua:734	"rpc"	"/home/salim/.local/share/nvim/mason/bin/cmake-language-server"	"stderr"	'    raise TypeCheckError(f"is not an instance of {qualified_name(origin_type)}")\ntypeguard.TypeCheckError: lsprotocol.types.TextDocumentSaveRegistrationOptions is not an instance of lsprotocol.types.SaveOptions\n'
```
Any idea why this might be happening ? 
I use stdio config given here
https://github.com/Decodetalkers/neocmakelsp#stdio

![image](https://github.com/Decodetalkers/neocmakelsp/assets/46407603/090d1610-54ef-4548-9cde-996df719747a)

**Comment by salimp2009** [comment]
I figure out I removed cmake-language-server then the error is gone and neocmake works. :)
